CREATE TABLE  "DATABASE_TYPE" 
   (    "ID" NUMBER(10,0) NOT NULL ENABLE, 
    "DATABASE_NAME" VARCHAR2(100), 
     CONSTRAINT "DATABASE_TYPE_PK" PRIMARY KEY ("ID") ENABLE
   ) ;CREATE TABLE  "CONNECTION_DETAIL" 
   (    "ID" NUMBER(10,0) NOT NULL ENABLE, 
    "DATABASE_TYPE" NUMBER(10,0) NOT NULL ENABLE, 
    "IP_ADDRESS" VARCHAR2(100) NOT NULL ENABLE, 
    "PORT" NUMBER(10,0) NOT NULL ENABLE, 
    "USERNAME" VARCHAR2(100) NOT NULL ENABLE, 
    "PASSWORD" VARCHAR2(100) NOT NULL ENABLE, 
    "USER_SCHEMA" VARCHAR2(100), 
    "CONNECTION_NAME" VARCHAR2(100), 
    "VALID_CONNECTION" VARCHAR2(10), 
    "SID" VARCHAR2(100), 
     CONSTRAINT "CONNECTION_DETAIL_PK" PRIMARY KEY ("ID") ENABLE, 
     CONSTRAINT "CONNECTION_DETAIL_UK1" UNIQUE ("CONNECTION_NAME", "DATABASE_TYPE", "IP_ADDRESS", "PORT", "USER_SCHEMA") ENABLE
   ) ;CREATE TABLE  "PRIME_METADATA_TABLES" 
   (    "ID" NUMBER(10,0) NOT NULL ENABLE, 
    "CONNECTION_ID" NUMBER(10,0) NOT NULL ENABLE, 
    "TABLE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
     CONSTRAINT "PRIME_METADATA_TABLES_PK" PRIMARY KEY ("ID") ENABLE, 
     CONSTRAINT "PRIME_METADATA_TABLES_CON" UNIQUE ("CONNECTION_ID", "TABLE_NAME") ENABLE
   ) ;CREATE TABLE  "PRIME_METADATA_COLUMNS" 
   (    "ID" NUMBER(10,0) NOT NULL ENABLE, 
    "TABLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
    "COLUMN_NAME" VARCHAR2(100) NOT NULL ENABLE, 
    "COLUMN_TYPE" VARCHAR2(100), 
     CONSTRAINT "PRIME_METADATA_COLUMNS_PK" PRIMARY KEY ("ID") ENABLE, 
     CONSTRAINT "PRIME_METADATA_COLUMNS_CON" UNIQUE ("TABLE_ID", "COLUMN_NAME") ENABLE
   ) ;ALTER TABLE  "CONNECTION_DETAIL" ADD CONSTRAINT "CONNECTION_DETAIL_FK" FOREIGN KEY ("DATABASE_TYPE")
      REFERENCES  "DATABASE_TYPE" ("ID") ON DELETE SET NULL ENABLE;ALTER TABLE  "PRIME_METADATA_COLUMNS" ADD CONSTRAINT "PRIME_METADATA_COLUMNS_FK" FOREIGN KEY ("TABLE_ID")
      REFERENCES  "PRIME_METADATA_TABLES" ("ID") ON DELETE CASCADE ENABLE;ALTER TABLE  "PRIME_METADATA_TABLES" ADD CONSTRAINT "PRIME_METADATA_TABLES_FK" FOREIGN KEY ("CONNECTION_ID")
      REFERENCES  "CONNECTION_DETAIL" ("ID") ENABLE; CREATE SEQUENCE   "PRIME_METADATA_TABLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "PRIME_METADATA_COLUMNS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "DATABASE_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "CONNECTION_DETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;